[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  [plugins.inputs]
    enableForms = true

# Add this if you're using Netlify Forms
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
