[build]
  command = "npm run build"
  publish = ".next"
  functions = ".next/functions"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "20.0.0"
  NPM_FLAGS = "--legacy-peer-deps"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@prisma/client"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
